[ACT-671] Handle App Clip export (#16)
* [ACT-671] Handle App Clip export

* added missing err check

* Do not force codesign identity

* Change certificate

* dep update

* Added nil check for clip

* moved check

* change test app branch

* fix prov profiles

* Add Xcode 12 check

* fixed profile entry

* changed test workflows to use sample artifacts

* changed branch of sample artifacts to master

* workflow fixes

* switch to development export method

* moved test_tvos

* moved xamarin

* xamarin fix

* reorganize workflows

* moved go ckecks

* removed xamarin from test workflow

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -5,42 +5,159 @@ app:
   envs:
   - RELEASE_VERSION: 1.0.1
   - ORIG_BITRISE_SOURCE_DIR: $BITRISE_SOURCE_DIR
+  - SAMPLE_ARTIFACTS_URL: https://github.com/bitrise-io/sample-artifacts.git
+  - SAMPLE_ARTIFACTS_BRANCH: master
+  - CUSTOM_PLIST: |-
+      <?xml version="1.0" encoding="UTF-8"?>
+      <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
+      <plist version="1.0">
+          <dict>
+            <key>compileBitcode</key>
+            <false/>
+            <key>destination</key>
+            <string>export</string>
+            <key>method</key>
+            <string>development</string>
+            <key>provisioningProfiles</key>
+            <dict>
+              <key>com.bitrise.code-sign-test</key>
+              <string>BitriseBot-Wildcard</string>
+              <key>com.bitrise.code-sign-test.share-extension</key>
+              <string>BitriseBot-Wildcard</string>
+              <key>com.bitrise.code-sign-test.watchkitapp</key>
+              <string>BitriseBot-Wildcard</string>
+              <key>com.bitrise.code-sign-test.watchkitapp.watchkitextension</key>
+              <string>BitriseBot-Wildcard</string>
+            </dict>
+            <key>signingCertificate</key>
+            <string>iPhone Developer: Dev Portal Bot Bitrise (E89JV3W9K4)</string>
+            <key>signingStyle</key>
+            <string>manual</string>
+            <key>stripSwiftSymbols</key>
+            <true/>
+            <key>teamID</key>
+            <string>72SA8V3WYL</string>
+            <key>thinning</key>
+            <string>&lt;none&gt;</string>
+          </dict>
+      </plist>
 
 workflows:
+  #usual go checks
+  _common_go_checks:
+    steps:
+    - go-list:
+    - golint:
+    - errcheck:
+    - go-test:
+
+
+  # Make sure to start with a clean setup
+  # Remove _tmp, switch workdir and install certs
+  _common_prepare:
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/bash
+            set -ex
+            rm -rf "$ORIG_BITRISE_SOURCE_DIR/_tmp"
+            mkdir -p "$ORIG_BITRISE_SOURCE_DIR/_tmp"
+    - change-workdir:
+        title: Switch working dir to _tmp dir
+        run_if: true
+        inputs:
+        - path: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
+        - is_create_path: true
+    - certificate-and-profile-installer:
+
+  # Clone sample artifacts
+  _common_clone:
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [[ -z "${SAMPLE_ARTIFACTS_URL}" ]]; then
+            echo "error: there is no SAMPLE_ARTIFACTS_URL env var specified"
+            exit 1
+            elif [[ -z "${SAMPLE_ARTIFACTS_COMMIT}" && -z "${SAMPLE_ARTIFACTS_BRANCH}" ]]; then
+            echo "error: can't checkout: there is no SAMPLE_ARTIFACTS_BRANCH or SAMPLE_ARTIFACTS_COMMIT env var specified"
+            exit 1
+            fi
+
+            git init
+            git remote add origin "${SAMPLE_ARTIFACTS_URL}" 
+            git fetch || exit 1
+
+            [[ -n "${SAMPLE_ARTIFACTS_COMMIT}" ]] && git checkout "${SAMPLE_ARTIFACTS_COMMIT}" || git checkout "${SAMPLE_ARTIFACTS_BRANCH}"
+
   # ----------------------------------------------------------------
   # --- Workflows for testing
-  test:
-    steps:
-    - go-list:
-    - golint:
-    - errcheck:
-    - go-test:
-    after_run:
-    - test_xamarin
-    - test_xcode
-    - test_tvos
 
+  # test on pre Xcode 12 
   test_legacy:
     steps:
-    - go-list:
-    - golint:
-    - errcheck:
-    - go-test:
+    - path::./:
+        title: Step Test - iOS archive
+        inputs:
+        - export_method: development
+        - archive_path: "./archives/ios.xcarchive"
+    - path::./:
+        title: Step Test - Custom plist
+        inputs:
+        - export_method: development
+        - archive_path: "./archives/ios.xcarchive"
+        - custom_export_options_plist_content: $CUSTOM_PLIST
+    before_run:
+    - _common_go_checks
+    - _common_prepare
+    - _common_clone
     after_run:
-    - test_xcode_7
+    - test_xamarin
+
+  # test on Xcode 12
+  test:
+    steps:
+    - path::./:
+        title: Step Test - iOS archive
+        inputs:
+        - export_method: development
+        - archive_path: "./archives/ios.xcarchive"
+    - path::./:
+        title: Step Test - Custom plist
+        inputs:
+        - export_method: development
+        - archive_path: "./archives/ios.xcarchive"
+        - custom_export_options_plist_content: $CUSTOM_PLIST
+    - path::./:
+        title: Step Test - TV OS
+        inputs:
+        - export_method: development
+        - archive_path: "./archives/TVOS.xcarchive"
+    - path::./:
+        title: Step Test - App Clip
+        inputs:
+        - export_method: development
+        - archive_path: "./archives/Fruta.xcarchive"
+        - product: "app-clip"
+    before_run:
+    - _common_go_checks
+    - _common_prepare
+    - _common_clone
 
   test_xamarin:
     envs:
+    - PRODUCT: "app"
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-xamarin-cross-platform.git
-    - BRANCH: developer_profile
+    - BRANCH: master
     - BITRISE_PROJECT_PATH: Multiplatform.sln
     - BITRISE_XAMARIN_CONFIGURATION: Release
     - BITRISE_XAMARIN_PLATFORM: iPhone
     - LEGACY: "no"
     before_run: 
     - _common_prepare
-    after_run:
-    - _common_test
     steps:
     - script:
         inputs:
@@ -66,251 +183,10 @@ workflows:
     - xamarin-archive:
         inputs:
         - project_type_whitelist: ios
-    - script:
-        title: ""
-        inputs:
-        - content: rm "$BITRISE_IPA_PATH"
-
-  test_xcode:
-    envs:
-    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-multi-target.git
-    - COMMIT: "ab36ed563bbc3125118e9f27df91474822dc0d46"
-    - BITRISE_PROJECT_PATH: code-sign-test.xcodeproj
-    - BITRISE_SCHEME: code-sign-test
-    - FORCE_TEAM_ID: 72SA8V3WYL
-    - FORCE_CODE_SIGN_IDENTITY: "iPhone Developer: Bitrise Bot"
-    - LEGACY: "no"
-    - PLIST: |-
-        <?xml version="1.0" encoding="UTF-8"?>
-        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
-        <plist version="1.0">
-            <dict>
-            	<key>compileBitcode</key>
-            	<false/>
-            	<key>destination</key>
-            	<string>export</string>
-            	<key>method</key>
-            	<string>development</string>
-            	<key>provisioningProfiles</key>
-            	<dict>
-            		<key>com.bitrise.code-sign-test</key>
-            		<string>Bitrise development - (com.bitrise.code-sign-test)</string>
-            		<key>com.bitrise.code-sign-test.share-extension</key>
-            		<string>Bitrise development - (com.bitrise.code-sign-test.share-extension)</string>
-            		<key>com.bitrise.code-sign-test.watchkitapp</key>
-            		<string>Bitrise development - (com.bitrise.code-sign-test.watchkitapp)</string>
-            		<key>com.bitrise.code-sign-test.watchkitapp.watchkitextension</key>
-            		<string>Bitrise development - (com.bitrise.code-sign-test.watchkitapp.watchkitextension)</string>
-            	</dict>
-            	<key>signingCertificate</key>
-            	<string>iPhone Developer: Bitrise Bot (VV2J4SV8V4)</string>
-            	<key>signingStyle</key>
-            	<string>manual</string>
-            	<key>stripSwiftSymbols</key>
-            	<true/>
-            	<key>teamID</key>
-            	<string>72SA8V3WYL</string>
-            	<key>thinning</key>
-            	<string>&lt;none&gt;</string>
-            </dict>
-        </plist>
-
-    before_run: 
-    - _common_prepare
-    after_run:
-    - _common_test
-    steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-
-            if [[ -z "${SAMPLE_APP_URL}" ]]; then
-            echo "error: there is no SAMPLE_APP_URL env var specified"
-            exit 1
-            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
-            echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
-            exit 1
-            fi
-
-            git init
-            git remote add origin "${SAMPLE_APP_URL}" 
-            git fetch || exit 1
-
-            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
-    - xcode-archive:
-        inputs:
-        - force_team_id: $FORCE_TEAM_ID
-        - force_code_sign_identity: $FORCE_CODE_SIGN_IDENTITY
-        - output_tool: xcodebuild
-    - script:
-        title: ""
-        inputs:
-        - content: rm "$BITRISE_IPA_PATH"
-
-  test_xcode_7:
-    envs:
-    - SAMPLE_APP_URL: https://github.com/bitrise-io/sample-apps-ios-simple-objc.git
-    - COMMIT: "65cd120bf4459c2881cfe2b731395b4efc53855d"
-    - BITRISE_PROJECT_PATH: ios-simple-objc/ios-simple-objc.xcodeproj
-    - BITRISE_SCHEME: ios-simple-objc
-    - FORCE_CODE_SIGN_IDENTITY: "iPhone Developer: Bitrise Bot"
-    - FORCE_TEAM_ID: 72SA8V3WYL
-    - LEGACY: "no"
-    - PLIST: |-
-        <?xml version="1.0" encoding="UTF-8"?>
-        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
-        <plist version="1.0">
-            <dict>
-            	<key>compileBitcode</key>
-            	<false/>
-            	<key>destination</key>
-            	<string>export</string>
-            	<key>method</key>
-            	<string>development</string>
-            	<key>provisioningProfiles</key>
-            	<dict>
-            		<key>Bitrise.ios-simple-objc</key>
-            		<string>BitriseBot-Wildcard</string>
-            	</dict>
-            	<key>signingCertificate</key>
-            	<string>iPhone Developer: Bitrise Bot</string>
-            	<key>signingStyle</key>
-            	<string>manual</string>
-            	<key>stripSwiftSymbols</key>
-            	<true/>
-            	<key>teamID</key>
-            	<string>72SA8V3WYL</string>
-            	<key>thinning</key>
-            	<string>&lt;none&gt;</string>
-            </dict>
-        </plist>
-
-    before_run: 
-    - _common_prepare
-    after_run:
-    - _common_test
-    steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-
-            if [[ -z "${SAMPLE_APP_URL}" ]]; then
-            echo "error: there is no SAMPLE_APP_URL env var specified"
-            exit 1
-            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
-            echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
-            exit 1
-            fi
-
-            git init
-            git remote add origin "${SAMPLE_APP_URL}" 
-            git fetch || exit 1
-
-            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
-    - xcode-archive:
-        inputs:
-        - force_team_id: $FORCE_TEAM_ID
-        - force_code_sign_identity: $FORCE_CODE_SIGN_IDENTITY
-        - output_tool: xcodebuild
-    - script:
-        title: ""
-        inputs:
-        - content: rm "$BITRISE_IPA_PATH"
-
-  test_tvos:
-    envs:
-    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-tvos-swift.git
-    - BRANCH: "master"
-    - BITRISE_PROJECT_PATH: NPO Live.xcworkspace
-    - BITRISE_SCHEME: NPO Live
-    - LEGACY: "no"
-    - PLIST: |-
-        <?xml version="1.0" encoding="UTF-8"?>
-        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
-        <plist version="1.0">
-            <dict>
-            	<key>compileBitcode</key>
-            	<false/>
-            	<key>destination</key>
-            	<string>export</string>
-            	<key>method</key>
-            	<string>development</string>
-            	<key>provisioningProfiles</key>
-            	<dict>
-            		<key>bdh.NPO-Live.bitrise.sample</key>
-            		<string>Bitrise development - (bdh.NPO-Live.bitrise.sample)</string>
-            	</dict>
-            	<key>signingCertificate</key>
-            	<string>iPhone Developer: Bitrise Bot</string>
-            	<key>signingStyle</key>
-            	<string>manual</string>
-            	<key>stripSwiftSymbols</key>
-            	<false/>
-            	<key>teamID</key>
-            	<string>72SA8V3WYL</string>
-            	<key>thinning</key>
-            	<string>&lt;none&gt;</string>
-            </dict>
-        </plist>
-
-
-    before_run: 
-    - _common_prepare
-    after_run:
-    - _common_test
-    steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/usr/bin/env bash
-
-            if [[ -z "${SAMPLE_APP_URL}" ]]; then
-            echo "error: there is no SAMPLE_APP_URL env var specified"
-            exit 1
-            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
-            echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
-            exit 1
-            fi
-
-            git init
-            git remote add origin "${SAMPLE_APP_URL}" 
-            git fetch || exit 1
-
-            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
-    - xcode-archive:
-        inputs:
-        - output_tool: xcodebuild
-    - script:
-        title: ""
-        inputs:
-        - content: rm "$BITRISE_IPA_PATH"
-
-  _common_prepare:
-    steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            rm -rf "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-            mkdir -p "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-    - change-workdir:
-        title: Switch working dir to _tmp dir
-        run_if: true
-        inputs:
-        - path: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-        - is_create_path: true
-    - certificate-and-profile-installer:
-
-  _common_test:
-    steps:
     - path::./:
         title: Step Test - Export Options
         inputs:
-        - use_legacy_export: $LEGACY
-        - custom_export_options_plist_content: $PLIST
+        - export_method: development
     - script:
         title: Output Test
         inputs:
