custom export options fix (#7)
* custom export options fix

* scriptify the git clone sample

* print fix

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -35,16 +35,24 @@ workflows:
     after_run:
     - _common_test
     steps:
-    - git-clone:
-        run_if: true
+    - script:
         inputs:
-        - repository_url: $SAMPLE_APP_URL
-        - clone_into_dir: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-        - commit: ""
-        - tag: ""
-        - branch: $BRANCH
-        - pull_request_id: ""
-        - clone_depth: ""
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+            echo "error: there is no SAMPLE_APP_URL env var specified"
+            exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+            echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+            exit 1
+            fi
+
+            git init
+            git remote add origin "${SAMPLE_APP_URL}" 
+            git fetch || exit 1
+
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
     - nuget-restore:
         inputs:
         - nuget_version: ""
@@ -75,16 +83,18 @@ workflows:
                 <key>provisioningProfiles</key>
                 <dict>
                     <key>com.bitrise.code-sign-test</key>
-                    <string>iOS Team Provisioning Profile: com.bitrise.code-sign-test</string>
+                    <string>BitriseBot-Wildcard</string>
                     <key>com.bitrise.code-sign-test.share-extension</key>
-                    <string>iOS Team Provisioning Profile: com.bitrise.code-sign-test.share-extension</string>
+                    <string>BitriseBot-Wildcard</string>
                     <key>com.bitrise.code-sign-test.watchkitapp</key>
-                    <string>iOS Team Provisioning Profile: com.bitrise.code-sign-test.watchkitapp</string>
+                    <string>BitriseBot-Wildcard</string>
                     <key>com.bitrise.code-sign-test.watchkitapp.watchkitextension</key>
-                    <string>iOS Team Provisioning Profile: com.bitrise.code-sign-test.watchkitapp.watchkitextension</string>
+                    <string>BitriseBot-Wildcard</string>
                 </dict>
                 <key>signingCertificate</key>
-                <string>iPhone Developer</string>
+                <string>iPhone Developer: Bitrise Bot (VV2J4SV8V4)</string>
+                <key>teamID</key>
+                <string>72SA8V3WYL</string>
             </dict>
         </plist>
     before_run: 
@@ -92,16 +102,24 @@ workflows:
     after_run:
     - _common_test
     steps:
-    - git-clone:
-        run_if: true
+    - script:
         inputs:
-        - repository_url: $SAMPLE_APP_URL
-        - clone_into_dir: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-        - commit: $COMMIT
-        - tag: ""
-        - branch: $BRANCH
-        - pull_request_id: ""
-        - clone_depth: ""
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+            echo "error: there is no SAMPLE_APP_URL env var specified"
+            exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+            echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+            exit 1
+            fi
+
+            git init
+            git remote add origin "${SAMPLE_APP_URL}" 
+            git fetch || exit 1
+
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
     - xcode-archive:
         inputs:
         - force_team_id: $FORCE_TEAM_ID
@@ -126,16 +144,24 @@ workflows:
     after_run:
     - _common_test
     steps:
-    - git-clone:
-        run_if: true
+    - script:
         inputs:
-        - repository_url: $SAMPLE_APP_URL
-        - clone_into_dir: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-        - commit: $COMMIT
-        - tag: ""
-        - branch: $BRANCH
-        - pull_request_id: ""
-        - clone_depth: ""
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+            echo "error: there is no SAMPLE_APP_URL env var specified"
+            exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+            echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+            exit 1
+            fi
+
+            git init
+            git remote add origin "${SAMPLE_APP_URL}" 
+            git fetch || exit 1
+
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
     - xcode-archive:
         inputs:
         - force_team_id: $FORCE_TEAM_ID
