Tool 1382/profile fix (#13)
* go-xcode dep update

* go-utils dep update

* update profile selection for exportOptrion logic

diff --git a/vendor/github.com/bitrise-io/steps-xcode-archive/bitrise.yml b/vendor/github.com/bitrise-io/steps-xcode-archive/bitrise.yml
--- a/vendor/github.com/bitrise-io/steps-xcode-archive/bitrise.yml
+++ b/vendor/github.com/bitrise-io/steps-xcode-archive/bitrise.yml
@@ -1,36 +1,37 @@
-format_version: "2"
+format_version: 7
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 
 app:
   envs:
-  - STEP_VERSION: 2.4.1
-
   - ORIG_BITRISE_SOURCE_DIR: $BITRISE_SOURCE_DIR
 
 workflows:
   # ----------------------------------------------------------------
   # --- workflow to Step Test
-  test:
-    before_run:
-    - go-tests
+  ci:
+    steps:
+    - go-list:
+    - golint:
+    - errcheck:
+    - go-test:
     after_run:
+    - test_cloudkit
     - test_objc
     - test_xcode_8
     - test_multi_target
-    - test_entitlements
+    - test_workspace
+    - test_tvos
 
-  test_xcode_7:
-    before_run:
-    - go-tests
+  test_cloudkit:
+    envs:
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-multi-target.git
+    - BRANCH: cloudkit
+    - BITRISE_PROJECT_PATH: code-sign-test.xcodeproj
+    - BITRISE_SCHEME: code-sign-test-Prod
+    - OUTPUT_TOOL: xcodebuild
+    - ICLOUD_CONTAINER_ENVIRONMENT: Production
     after_run:
-    - test_objc
-
-  test_xcode_8:
-    before_run:
-    - go-tests
-    after_run:
-    - test_objc
-    - test_xcode_8
+    - _common
 
   test_objc:
     envs:
@@ -47,10 +48,11 @@ workflows:
   test_xcode_8:
     envs:
     - SAMPLE_APP_URL: https://github.com/bitrise-samples/ios-xcode-8.0.git
-    - COMMIT: "52ca16a9cead25be8c95c54e7fd53ce8fd945330"
+    - BRANCH: "swift_version"
     - BITRISE_PROJECT_PATH: ios-xcode-8.0/ios-xcode-8.0.xcodeproj
     - BITRISE_SCHEME: ios-xcode-8.0
-    - FORCE_TEAM_ID: 72SA8V3WYL
+    - FORCE_CODE_SIGN_IDENTITY: ""
+    - FORCE_TEAM_ID: ""
     - OUTPUT_TOOL: xcpretty
     after_run:
     - _common
@@ -66,14 +68,28 @@ workflows:
     after_run:
     - _common
 
-  test_entitlements:
+  test_workspace:
     envs:
-    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-multi-target.git
-    - COMMIT: "0562d74e591e1cfdf6cdfeb603880f64f31f000c"
-    - BITRISE_PROJECT_PATH: code-sign-test.xcodeproj
-    - BITRISE_SCHEME: code-sign-test
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-ios-workspace-swift.git
+    - COMMIT: "1360413258cc7f6a8676c17f060ff39899fc28b1"
+    - BITRISE_PROJECT_PATH: sample-apps-ios-workspace-swift.xcworkspace
+    - BITRISE_SCHEME: sample-apps-ios-workspace-swift
+    - FORCE_CODE_SIGN_IDENTITY: "iPhone Developer: Bitrise Bot"
+    - PROV_PROFILE_SPECIFIER: "BitriseBot-Wildcard"
+    - FORCE_TEAM_ID: 72SA8V3WYL
+    after_run:
+    - _common
+
+  test_tvos:
+    envs:
+    - SAMPLE_APP_URL: https://github.com/bitrise-samples/sample-apps-tvos-swift.git
+    - BRANCH: "master"
+    - BITRISE_PROJECT_PATH: NPO Live.xcworkspace
+    - BITRISE_SCHEME: "NPO Live"
     - FORCE_CODE_SIGN_IDENTITY: ""
     - FORCE_TEAM_ID: ""
+    - PROV_PROFILE_SPECIFIER: ""
+    - OUTPUT_TOOL: xcpretty
     after_run:
     - _common
 
@@ -92,23 +108,33 @@ workflows:
         inputs:
         - path: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
         - is_create_path: true
-    - git-clone:
-        run_if: true
+    - script:
         inputs:
-        - repository_url: $SAMPLE_APP_URL
-        - clone_into_dir: "$ORIG_BITRISE_SOURCE_DIR/_tmp"
-        - commit: $COMMIT
-        - tag: ""
-        - branch: ""
-        - pull_request_id: ""
-        - clone_depth: ""
+        - content: |-
+            #!/usr/bin/env bash
+
+            if [[ -z "${SAMPLE_APP_URL}" ]]; then
+              echo "error: there is no SAMPLE_APP_URL env var specified"
+              exit 1
+            elif [[ -z "${COMMIT}" && -z "${BRANCH}" ]]; then
+              echo "error: can't checkout: there is no BRANCH or COMMIT env var specified"
+              exit 1
+            fi
+
+            git init
+            git remote add origin "${SAMPLE_APP_URL}"
+            git fetch || exit 1
+            [[ -n "${COMMIT}" ]] && git checkout "${COMMIT}" || git checkout "${BRANCH}"
+
     - certificate-and-profile-installer:
     - path::./:
         inputs:
-        - output_tool: xcodebuild
+        - output_tool: $OUTPUT_TOOL
         - force_code_sign_identity: $FORCE_CODE_SIGN_IDENTITY
         - force_team_id: $FORCE_TEAM_ID
         - verbose_log: "yes"
+        - force_provisioning_profile_specifier: $PROV_PROFILE_SPECIFIER
+        - icloud_container_environment: $ICLOUD_CONTAINER_ENVIRONMENT
     - script:
         title: Output (generated by the Step) tests
         is_always_run: true
@@ -123,67 +149,6 @@ workflows:
             echo "-> BITRISE_XCARCHIVE_PATH:             $BITRISE_XCARCHIVE_PATH"
             echo "-> BITRISE_IDEDISTRIBUTION_LOGS_PATH:  $BITRISE_IDEDISTRIBUTION_LOGS_PATH"
             echo "-> BITRISE_XCODE_RAW_RESULT_TEXT_PATH: $BITRISE_XCODE_RAW_RESULT_TEXT_PATH"
-
-  go-tests:
-    before_run:
-    - _install-test-tools
-    steps:
-    - script:
-        title: Export go files to test
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-
-            no_vendor_paths="$(go list ./... | grep -v vendor)"
-            envman add --key GOLIST_WITHOUT_VENDOR --value "$no_vendor_paths"
-    - script:
-        title: Err check
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-
-            errcheck -asserts=true -blank=true $GOLIST_WITHOUT_VENDOR
-    - script:
-        title: Go lint
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-
-            while read -r line; do
-              echo "-> Linting: $line"
-              golint_out="$(golint $line)"
-              if [[ "${golint_out}" != "" ]] ; then
-                echo "=> Golint issues found:"
-                echo "${golint_out}"
-                exit 1
-              fi
-            done <<< "$GOLIST_WITHOUT_VENDOR"
-    - script:
-        title: Go test
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-
-            go test $(go list ./... | grep -v vendor)
-
-  _install-test-tools:
-    steps:
-    - script:
-        title: Install required testing tools
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-
-            # Check for unhandled errors
-            go get -u -v github.com/kisielk/errcheck
-
-            # Go lint
-            go get -u -v github.com/golang/lint/golint
 
   # ----------------------------------------------------------------
   # --- Utility workflows
@@ -203,20 +168,6 @@ workflows:
             dep ensure -v -update
 
   # ----------------------------------------------------------------
-  # --- workflows to create Release
-  create-release:
-    steps:
-    - script:
-        title:
-        inputs:
-        - content: |
-            #!/bin/bash
-            set -ex
-            go get -u github.com/bitrise-tools/releaseman
-            export CI=true
-            releaseman create --version $STEP_VERSION
-
-  # ----------------------------------------------------------------
   # --- workflow to Share this step into a Step Library
   audit-this-step:
     steps:
@@ -226,43 +177,3 @@ workflows:
             #!/bin/bash
             set -ex
             stepman audit --step-yml ./step.yml
-
-  share-this-step:
-    envs:
-      # if you want to share this step into a StepLib
-      - MY_STEPLIB_REPO_FORK_GIT_URL: $MY_STEPLIB_REPO_FORK_GIT_URL
-      - STEP_ID_IN_STEPLIB: xcode-archive
-      - STEP_GIT_VERION_TAG_TO_SHARE: $STEP_VERSION
-      - STEP_GIT_CLONE_URL: https://github.com/bitrise-io/steps-xcode-archive.git
-    description: |-
-      If this is the first time you try to share a Step you should
-      first call: $ bitrise share
-
-      This will print you a guide, and information about how Step sharing
-      works. Please read it at least once!
-
-      As noted in the Step sharing guide you'll have to fork the
-      StepLib you want to share this step into. Once you're done with forking
-      the repository you should set your own fork's git clone URL
-      in the `.bitrise.secrets.yml` file, or here in the `envs` section,
-      as the value of the `MY_STEPLIB_REPO_FORK_GIT_URL` environment.
-
-      You're now ready to share this Step, just make sure that
-      the `STEP_ID_IN_STEPLIB` and `STEP_GIT_VERION_TAG_TO_SHARE`
-      environments are set to the desired values!
-
-      To share this Step into a StepLib you can just run: $ bitrise run share-this-step
-
-      Once it finishes the only thing left is to actually create a Pull Request,
-      the way described in the guide printed at the end of the process.
-    before_run:
-    - audit-this-step
-    steps:
-    - script:
-        inputs:
-        - content: |-
-            #!/bin/bash
-            set -ex
-            bitrise share start -c ${MY_STEPLIB_REPO_FORK_GIT_URL}
-            bitrise share create --stepid ${STEP_ID_IN_STEPLIB} --tag ${STEP_GIT_VERION_TAG_TO_SHARE} --git ${STEP_GIT_CLONE_URL}
-            bitrise share finish
