Mob 112 automatic signing (#30)
* Migrate to ideal step code structure

* Update dsym export

* Move ide distribution logs export

* Move utility functions to utils.go

* Lint fixes

* Add auto codesign inputs

* Create codesign manager

* Set auth params on export command

* Pull latest go-xcode package

* Pull go-xcode and add auto-codesign e2e tests

* Update e2e tests

* Pull master go-xcode

* Remove RunOpts as it duplicates Config

* Separate e2e tests

* Fix yaml lint issue

* Update README

* Update main.go

Co-authored-by: lpusok <7979773+lpusok@users.noreply.github.com>

* Add app-clip test

* Update 'Multi Target xcodebuild auto signing' e2e test case run_if condition

* Run app-clip test with bitrise-managed signing

* Use sample-artifacts from master branch

Co-authored-by: lpusok <7979773+lpusok@users.noreply.github.com>

diff --git a/e2e/bitrise.yml b/e2e/bitrise.yml
--- a/e2e/bitrise.yml
+++ b/e2e/bitrise.yml
@@ -4,10 +4,9 @@ default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 app:
   envs:
   # secrets
+  - BITFALL_APPLE_IOS_CERTIFICATE_URL_LIST: $BITFALL_APPLE_IOS_CERTIFICATE_URL_LIST
+  - BITFALL_APPLE_IOS_CERTIFICATE_PASSPHRASE_LIST: $BITFALL_APPLE_IOS_CERTIFICATE_PASSPHRASE_LIST
   - BITFALL_APPLE_PROVISIONING_PROFILE_URL_LIST: $BITFALL_APPLE_PROVISIONING_PROFILE_URL_LIST
-
-  - RELEASE_VERSION: 1.0.1
-  - ORIG_BITRISE_SOURCE_DIR: $BITRISE_SOURCE_DIR
   - SAMPLE_ARTIFACTS_URL: https://github.com/bitrise-io/sample-artifacts.git
   - SAMPLE_ARTIFACTS_BRANCH: master
   - CUSTOM_PLIST: |-
@@ -46,10 +45,84 @@ app:
       </plist>
 
 workflows:
+  test_auto_codesign_with_manual_assets:
+    before_run:
+    - _setup
+    steps:
+    - certificate-and-profile-installer:
+        inputs:
+        - certificate_url: $BITFALL_APPLE_IOS_CERTIFICATE_URL_LIST
+        - certificate_passphrase: $BITFALL_APPLE_IOS_CERTIFICATE_PASSPHRASE_LIST
+        - provisioning_profile_url: $BITFALL_APPLE_PROVISIONING_PROFILE_URL_LIST
+        - install_defaults: "no"
+    - path::./:
+        title: Step Test - Multi Target API Key auto signing
+        inputs:
+        - distribution_method: development
+        - archive_path: ./archives/Fruta.xcarchive
+        - product: app
+        - automatic_code_signing: api-key
+        - min_profile_validity: 30
+        - certificate_url_list: $BITFALL_APPLE_IOS_CERTIFICATE_URL_LIST
+        - passphrase_list: $BITFALL_APPLE_IOS_CERTIFICATE_PASSPHRASE_LIST
+
+  test_auto_codesign:
+    before_run:
+    - _setup
+    - _expose_xcode_version
+    steps:
+    - script:
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ${XCODE_MAJOR_VERSION} -lt 13 ]]; then
+              echo "This test case requires Xcode >= 13, skipping..."
+              exit 0
+            fi
+            envman add --key XCODE_MAJOR_VERSION_AT_LEAST_13 --value "true"
+    - path::./:
+        title: Step Test - Multi Target xcodebuild auto signing
+        run_if: |-
+          {{ enveq "XCODE_MAJOR_VERSION_AT_LEAST_13" "true" }}
+        inputs:
+        - distribution_method: development
+        - archive_path: ./archives/Fruta-managed.xcarchive
+        - product: app
+        - automatic_code_signing: api-key
+        - certificate_url_list: $BITFALL_APPLE_IOS_CERTIFICATE_URL_LIST
+        - passphrase_list: $BITFALL_APPLE_IOS_CERTIFICATE_PASSPHRASE_LIST
+    - path::./:
+        title: Step Test - Multi Target API Key auto signing
+        inputs:
+        - distribution_method: development
+        - archive_path: ./archives/Fruta.xcarchive
+        - product: app-clip
+        - automatic_code_signing: api-key
+        - min_profile_validity: 30
+        - certificate_url_list: $BITFALL_APPLE_IOS_CERTIFICATE_URL_LIST
+        - passphrase_list: $BITFALL_APPLE_IOS_CERTIFICATE_PASSPHRASE_LIST
+    - path::./:
+        title: Step Test - TV OS Apple ID auto signing
+        inputs:
+        - distribution_method: development
+        - archive_path: ./archives/TVOS.xcarchive
+        - min_profile_validity: 30
+        - automatic_code_signing: apple-id
+        - certificate_url_list: $BITFALL_APPLE_IOS_CERTIFICATE_URL_LIST
+        - passphrase_list: $BITFALL_APPLE_IOS_CERTIFICATE_PASSPHRASE_LIST
+
+
   test_ipa_exports:
     before_run:
     - _setup
     steps:
+    - certificate-and-profile-installer:
+        inputs:
+        - certificate_url: $BITFALL_APPLE_IOS_CERTIFICATE_URL_LIST
+        - certificate_passphrase: $BITFALL_APPLE_IOS_CERTIFICATE_PASSPHRASE_LIST
+        - provisioning_profile_url: $BITFALL_APPLE_PROVISIONING_PROFILE_URL_LIST
+        - install_defaults: "no"
     - path::./:
         title: Step Test - iOS archive
         inputs:
@@ -76,23 +149,43 @@ workflows:
   _setup:
     steps:
     - script:
-        title: Clean _tmp dir
+        title: Clean _tmp an profile dir
         inputs:
         - content: |-
             #!/usr/bin/env bash
             set -e
             rm -rf ./_tmp
+            rm -rf ~/Library/MobileDevice/Provisioning Profiles
     - change-workdir:
         title: Switch working dir to _tmp
         inputs:
         - path: ./_tmp
         - is_create_path: true
-    - certificate-and-profile-installer:
-        inputs:
-        - provisioning_profile_url: $BITFALL_APPLE_PROVISIONING_PROFILE_URL_LIST
     - git::https://github.com/bitrise-steplib/bitrise-step-simple-git-clone.git@master:
         title: Clone sample app
         inputs:
         - repository_url: $SAMPLE_ARTIFACTS_URL
         - clone_into_dir: .
         - branch: $SAMPLE_ARTIFACTS_BRANCH
+
+  _expose_xcode_version:
+    steps:
+    - script:
+        title: Expose Xcode major version
+        inputs:
+        - content: |-
+            #!/bin/env bash
+            set -e
+            if [[ ! -z "$XCODE_MAJOR_VERSION" ]]; then
+              echo "Xcode major version already exposed: $XCODE_MAJOR_VERSION"
+              exit 0
+            fi
+            version=`xcodebuild -version`
+            regex="Xcode ([0-9]*)."
+            if [[ ! $version =~ $regex ]]; then
+              echo "Failed to determine Xcode major version"
+              exit 1
+            fi
+            xcode_major_version=${BASH_REMATCH[1]}
+            echo "Xcode major version: $xcode_major_version"
+            envman add --key XCODE_MAJOR_VERSION --value $xcode_major_version
